### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by gersongoulart** [JarvisPrestidge/VSCode-Material-Theme#4]
Thank you so  much for this! Exactly what I needed to help the move from ST to VS!

I'd like to suggest adding a bit of documentation on how to get it set up and running (for new users of the editor). I had to install Sublime Babel and Material Icon Theme to get it to look just right...

Just a suggestion! Thanks again!

**Comment by JarvisPrestidge** [comment]
Thanks for the comment, although I won't be supporting the theme anymore since the original creator "Mattia Astorino" has just released an offical port which supersedes this.

I do agree with what you recommend though, but Mattia has done exactly that on his github :smiley:  I'll most likely remove the plugin from vscode and the link for the new theme is as follows: [Material Theme - official](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme)
